feat: support running gRPC test cases
LinuxSuRen/api-testing pull request #160
Opened 2023-08-05 08:50 UTC by Ink-33

## Introducing gRPC test case support
In #81, we disscuss about gRPC test cases. 

In order to support gRPC, some new fields has been added into testsuite schema. see `docs/api-testing-schema.json`

Here is a gRPC testsuite sample in `sample/grpc-sample.yaml`

This is still some work should be done. Please feel free to review.

- [ ] support server reflection
- [ ] add test for gRPC.go

2023-08-05 09:04 UTC, Ink-33 commented on pkg/runner/grpc.go
> +			errors.Join(errlist, fmt.Errorf("field %s: field %s is not exist", field, k))
`errors.Join` is added in go 1.20. I will try to find another to replace it.

2023-08-07 13:13 UTC, LinuxSuRen requested changes

2023-08-13 12:14 UTC, LinuxSuRen requested changes
LGTM for the most part. But you still need to handle the license header issue.

2023-08-13 12:14 UTC, LinuxSuRen commented on pkg/runner/runner_factory.go
> +package runner
Please add [the license header](https://github.com/LinuxSuRen/api-testing/blob/master/LICENSE) into the every new files. See also https://github.com/LinuxSuRen/api-testing/blob/e2f2d323f03eee2698c0c274252a8880b8222f29/pkg/secret/types.go

2023-08-13 12:14 UTC, LinuxSuRen commented on pkg/testing/case.go
> +	ServerReflection bool     `yaml:"server_reflection,omitempty" json:"server_reflection,omitempty"`
I prefer to use the camel case style.

2023-08-13 13:02 UTC, LinuxSuRen approved these changes
Good job!

2023-08-13 13:09 UTC, merged